create table "SCPDATA" (
	"NAME" VARCHAR NOT NULL PRIMARY KEY,
	"AETITLE" VARCHAR NOT NULL,
	"PORT" INTEGER NOT NULL
);

create table "METADATA" (
	"PATIENTNAME" VARCHAR NOT NULL,
	"PATIENTID" VARCHAR NOT NULL,
	"STUDYINSTANCEUID" VARCHAR NOT NULL,
	"STUDYDATE" VARCHAR NOT NULL,
	"SERIESINSTANCEUID" VARCHAR NOT NULL,
	"SERIESDATE" VARCHAR NOT NULL,
	"SOPINSTANCEUID" VARCHAR NOT NULL,
	"FILENAME" VARCHAR NOT NULL PRIMARY KEY
);
